services:
  mongodb:
    image: mongo:8
    container_name: mongo_local
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: "Asia/Shanghai"
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
